// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Graph edge representation shared between the CLI and frontend.
 */
export type GraphEdge = { source: string, target: string, };
