// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphConfig } from "./GraphConfig";
import type { GraphEdge } from "./GraphEdge";
import type { GraphNode } from "./GraphNode";

/**
 * Complete graph data payload passed from the CLI to the frontend.
 */
export type GraphData = { nodes: Array<GraphNode>, edges: Array<GraphEdge>, config?: GraphConfig, };
