// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Graph node representation shared between the CLI and frontend.
 */
export type GraphNode = { id: string, type: "module" | "script" | "namespace" | "namespace_group", is_orphan: boolean, highlighted?: boolean, parent?: string, };
