// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Graph configuration for visualization consumers.
 */
export type GraphConfig = { include_orphans: boolean, include_namespaces: boolean, highlighted_modules?: Array<string>, };
