import './styles/main.css';
import type { GraphData } from './types';

// This will be replaced with actual WASM imports later
// For now, just log that we're loaded
console.log('Deptree frontend loaded');

async function main() {
  // Check if graph data is available
  if (!window.__GRAPH_DATA__) {
    console.error('No graph data found! Expected window.__GRAPH_DATA__ to be set.');
    document.body.innerHTML = `
      <div style="padding: 20px; font-family: sans-serif;">
        <h1>Error: No Graph Data</h1>
        <p>Expected graph data to be embedded in window.__GRAPH_DATA__</p>
        <p>This page is meant to be generated by the deptree-utils CLI tool.</p>
      </div>
    `;
    return;
  }

  const graphData: GraphData = window.__GRAPH_DATA__;
  console.log('Graph data loaded:', {
    nodes: graphData.nodes.length,
    edges: graphData.edges.length,
    config: graphData.config,
  });

  // TODO: Initialize WASM module
  // TODO: Initialize Cytoscape
  // TODO: Setup UI event handlers

  // For now, just show a placeholder
  const container = document.getElementById('cy');
  if (container) {
    container.innerHTML = `
      <div style="display: flex; align-items: center; justify-content: center; height: 100%; color: #666;">
        <div style="text-align: center;">
          <h2>Graph Visualization</h2>
          <p>${graphData.nodes.length} nodes, ${graphData.edges.length} edges</p>
          <p style="font-size: 14px; color: #999;">Frontend initialization in progress...</p>
        </div>
      </div>
    `;
  }
}

main();
