import './styles/main.css';
import type { GraphData } from './types';
import { initializeCytoscape } from './cytoscape-manager';
import { LayoutManager } from './layout-manager';
import { FilterState } from './filter-state';
import { ModuleSelector } from './ui/module-selector';
import { setupUIEventHandlers } from './ui/controls';

// Import WASM module (will be available after build)
// @ts-ignore - WASM module will be generated by wasm-pack
import init, { GraphProcessor } from './wasm/deptree_wasm.js';

console.log('Deptree frontend loaded');

async function main() {
  // Check if graph data is available
  if (!window.__GRAPH_DATA__) {
    console.error('No graph data found! Expected window.__GRAPH_DATA__ to be set.');
    document.body.innerHTML = `
      <div style="padding: 20px; font-family: sans-serif;">
        <h1>Error: No Graph Data</h1>
        <p>Expected graph data to be embedded in window.__GRAPH_DATA__</p>
        <p>This page is meant to be generated by the deptree-utils CLI tool.</p>
      </div>
    `;
    return;
  }

  const graphData: GraphData = window.__GRAPH_DATA__;
  console.log('Graph data loaded:', {
    nodes: graphData.nodes.length,
    edges: graphData.edges.length,
    config: graphData.config,
  });

  try {
    // Initialize WASM module
    await init();
    console.log('WASM module initialized');

    // Create graph processor
    const processor = new GraphProcessor(JSON.stringify(graphData));

    // Compute all-pairs distances
    const distances = processor.compute_all_distances() as DistanceMap;
    console.log('Distances computed');

    // Initialize Cytoscape
    const cy = initializeCytoscape(graphData, distances);
    console.log('Cytoscape initialized');

    // Initialize layout manager
    const layoutManager = new LayoutManager(cy);
    layoutManager.renderSettingsUI();

    // Initialize filter state
    const filterState = new FilterState(processor, cy);

    // Setup module selectors
    const allModuleNames = cy
      .nodes()
      .map((n) => n.id())
      .sort();

    const upstreamSelector = new ModuleSelector('upstream-modules', allModuleNames, (selected) => {
      // Clear existing upstream roots
      filterState.clearUpstreamRoots();
      // Add new ones
      selected.forEach((moduleId) => filterState.addUpstreamRoot(moduleId));
    });

    const downstreamSelector = new ModuleSelector('downstream-modules', allModuleNames, (selected) => {
      // Clear existing downstream roots
      filterState.clearDownstreamRoots();
      // Add new ones
      selected.forEach((moduleId) => filterState.addDownstreamRoot(moduleId));
    });

    // Setup UI event handlers
    setupUIEventHandlers(cy, layoutManager, filterState);

    // Setup add module buttons
    const addUpstreamBtn = document.getElementById('add-upstream');
    if (addUpstreamBtn) {
      addUpstreamBtn.addEventListener('click', () => {
        const moduleName = prompt('Enter module name:');
        if (moduleName && allModuleNames.includes(moduleName)) {
          upstreamSelector.addModule(moduleName);
        } else if (moduleName) {
          alert(`Module "${moduleName}" not found`);
        }
      });
    }

    const addDownstreamBtn = document.getElementById('add-downstream');
    if (addDownstreamBtn) {
      addDownstreamBtn.addEventListener('click', () => {
        const moduleName = prompt('Enter module name:');
        if (moduleName && allModuleNames.includes(moduleName)) {
          downstreamSelector.addModule(moduleName);
        } else if (moduleName) {
          alert(`Module "${moduleName}" not found`);
        }
      });
    }

    // Apply initial layout
    layoutManager.applyLayout(false);

    console.log('Frontend initialization complete');
  } catch (error) {
    console.error('Failed to initialize frontend:', error);
    const container = document.getElementById('cy');
    if (container) {
      container.innerHTML = `
        <div style="padding: 20px; font-family: sans-serif; color: #d32f2f;">
          <h2>Initialization Error</h2>
          <p>${error}</p>
          <p style="font-size: 12px; color: #666;">Check the browser console for more details.</p>
        </div>
      `;
    }
  }
}

main();
